name: bazel-test

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1

      - name: mount cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel-disk-cache" # this should match .bazelrc
          key: ${{ runner.os }}-bazel-disk-cache

      - name: test
        run: bazel test //...

      - name: build
        run: bazel build //...
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
