name: Publish

on:
  push:
    tags:
      - v*.*.*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make test DOCKER_FLAGS=

  build-publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: make
      - run: npm publish --access=public --verbose
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
